user1 = User.create!(username:"queenC",password:"cersei",name:"Cersei Lannister",about_me:"I am a doting mother of three children. My hobbies include world politics and cultivating close relationships with my friends and relatives, especially my brother. Personal motto: The more people you love, the weaker you are. The only thing I love is power and I kill anyone who tries to take it from me.",image_url:"http://res.cloudinary.com/dbsxgncvx/image/upload/c_fill,h_400,w_400/v1478241047/Users/cersei2.jpg",allegiance_id:1)
user2 = User.create!(username:"LordCommander",password:"jonsno",name:"Jon Snow",about_me:"According to my ex-girlfriend, I know nothing.",image_url:"http://res.cloudinary.com/dbsxgncvx/image/upload/c_fill,h_400,w_400/v1478068317/Users/Jon_Kill_the_Boy.jpg",allegiance_id:2)
user3 = User.create!(username:"LittleDove",password:"sansas",name:"Sansa Stark",about_me:"Never a bridesmaid, always a bride.",image_url:"http://res.cloudinary.com/dbsxgncvx/image/upload/c_fill,h_400,w_400/v1478240271/Users/sansa.jpg",allegiance_id:2)
user4 = User.create!(username:"MotherOfDragons",password:"daener",name:"Daenerys Targaryen",about_me:"I will take what's mine.",image_url:"http://res.cloudinary.com/dbsxgncvx/image/upload/c_fill,h_400,w_400/v1478240565/Users/daenerys5.jpg",allegiance_id:3)
user5 = User.create!(username:"NoOne",password:"jaqenh",name:"Jaqen H'ghar",about_me:"",image_url:"http://res.cloudinary.com/dbsxgncvx/image/upload/c_fill,h_400,w_400/v1478240491/Users/jaqenh_ghar.jpg")
# user6 = User.create!(username:"LordFrey",password:"walder",name:"Walder Frey",about_me:"",image_url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478069095/Users/walderfrey.jpg",allegiance_id:8)
# user7 = User.create!(username:"LordOfRiverrun",password:"edmure",name:"Edmure Tully",about_me:"",image_url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478069012/Users/edmuretully.jpg",allegiance_id:5)
# user8 = User.create!(username:"YouKnowNothing",password:"ygritt",name:"Ygritte",about_me:"",image_url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478063339/Users/ygritte.jpg")
# user9 = User.create!(username:"KahlDreamy",password:"kahldr",name:"Kahl Drogo",about_me:"",image_url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478063328/Users/kahldrogo.jpg")
# user10 = User.create!(username:"pIMP",password:"tryion",name:"Tyrion Lannister",about_me:"I am incredibly knowledgeable about two things: Wine and Whores. I am well read and well traveled. I spent my youth at Casterly Rock, but in the past few years I've been to Castle Black, Winterfell, The Eyrie, Kings Landing, Pentos, Volantis and Meereen. I'm am quite the conversationalist, using my words to get me both in and out of trouble. I'm an international man of mystery.",image_url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478069658/Users/tyrion.jpg",allegiance_id:3)
# user11 = User.create!(username:"QueenOfThorns",password:"olenna",name:"Olenna Tyrell",about_me:"",image_url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478063333/Users/olenna.jpg",allegiance_id:6)
# user12 = User.create!(username:"Kingslayer",password:"jaimel",name:"Jaime Lannister",about_me:"",image_url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478069767/Users/jaime2.jpg",allegiance_id:1)
# user13 = User.create!(username:"FaithOfTheSeven",password:"highsp",name:"High Sparrow",about_me:"",image_url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478063365/Users/highsparrow.png")
# user14 = User.create!(username:"MoonDoor",password:"lysaar",name:"Lysa Arryn",about_me:"",image_url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478063333/Users/lysaarryn.jpg",allegiance_id:10)
# user15 = User.create!(username:"Reek",password:"theong",name:"Theon Greyjoy",about_me:"",image_url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478069869/Users/theon.jpg",allegiance_id:9)
# user16 = User.create!(username:"Littlefinger",password:"petyrb",name:"Petyr Baelish",about_me:"",image_url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478063328/Users/littlefinger.jpg")
# user17 = User.create!(username:"BastardOfBolton",password:"ramsay",name:"Ramsay Bolton",about_me:"",image_url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478063333/Users/ramsay.jpg",allegiance_id:11)
# user18 = User.create!(username:"RedPriestess",password:"melisa",name:"Melisandre",about_me:"",image_url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478063332/Users/melisandre.jpg")
# user19 = User.create!(username:"SandSnake",password:"ellari",name:"Ellaria Sand",about_me:"",image_url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478063323/Users/ellaria.jpg",allegiance_id:12)
# user20 = User.create!(username:"WarriorOfLight",password:"stanni",name:"Stannis Baratheon",about_me:"",image_url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478070020/Users/stannis.jpg",allegiance_id:4)
# user21 = User.create!(username:"Sam",password:"samwel",name:"Samwell Tarly",about_me:"",image_url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478070175/Users/sam.jpg",allegiance_id:7)
# user22 = User.create!(username:"kingB",password:"robert",name:"Robert Baratheon",about_me:"I went hunting one day and ruing everything for everyone.",image_url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478063341/Users/robert.jpg",allegiance_id:4)
# user23 = User.create!(username:"BtheBeauty",password:"brienn",name:"Brienne",about_me:"",image_url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478063328/Users/brienne.jpg",allegiance_id:2)
# user24 = User.create!(username:"ladyC",password:"ladycr",name:"Lady Crane",about_me:"",image_url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478070446/Users/ladycrane.jpg")
# user25 = User.create!(username:"Eunuch",password:"varys1",name:"Varys",about_me:"",image_url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478063337/Users/varys2.jpg",allegiance_id:3)
# user26 = User.create!(username:"Needle",password:"aryas",name:"Arya Stark",about_me:"I was raised at Winterfell but have been on my own from an early age.  I have been traveling the world working on my "kill list", but not to worry I'm quite the pleasant house guest for those that are not on my "list".  I am happy to help with cooking and cleaning in exchange for a roof over my head.  My hobbies include fencing, archery and vengeance.",image_url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478063319/Users/arya.jpg",allegiance_id:2)
# user27 = User.create!(username:"TheRealQueen",password:"margae",name:"Margaery Tyrell",about_me:"",image_url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478070578/Users/margaery.png",allegiance_id:6)
# user28 = User.create!(username:"TheMountain",password:"gregor",name:"Gregor Clegane",about_me:"",image_url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478070616/Users/mountain.jpg",allegiance_id:1)
# user29 = User.create!(username:"EvilKing",password:"joffre",name:"Joffrey Baratheon",about_me:"",image_url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478070651/Users/joffrey.jpg",allegiance_id:1)
# user30 = User.create!(username:"hodorhodor",password:"hodor1",name:"Hodor",about_me:"Hodor hodor hodor hodor",image_url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478070785/Users/hodor.jpg",allegiance_id:2)

place1 = Place.create!(host_id:1,title:"The Red Keep",lng:1,lat:1,description:"King's Landing palace",price_per_night:1400,region_id:1,number_rooms:24,number_beds:32,max_guests:40,property_type:"Palace",house_rules:"a",allegiance_id:1,stars:5)
place2 = Place.create!(host_id:2,title:"Castle Black",lng:2,lat:2,description:"home to Knight's Watch", price_per_night: 80,region_id:6,number_rooms:1,number_beds:1,max_guests:16,property_type:"Castle",house_rules:"a",stars:3)
place3 = Place.create!(host_id:3,title:"Winterfell",lng:3,lat:3,description:"Stark house",price_per_night:40,region_id:2,number_rooms:1,number_beds:1,max_guests:10,property_type:"Castle",house_rules:"a",allegiance_id:2,stars:5)
place4 = Place.create!(host_id:4,title:"Great Pyramid",lng:4,lat:4,description:"Meereen",price_per_night:180,region_id:10,number_rooms:1,number_beds:1,max_guests:20,property_type:"Pyramid",house_rules:"a",stars:5)
place5 = Place.create!(host_id:5,title:"House of Black and White",lng:5,lat:5,description:"has hall of faces",price_per_night:50,region_id:3,number_rooms:1,number_beds:1,max_guests:1,property_type:"House",house_rules:"a",stars:2)
# place6 = Place.create!(host_id:6,title:"The Twins",lng:,lat:,description:"",price_per_night:,region_id:7,number_rooms:,number_beds:,max_guests:,property_type:"",house_rules:"",allegiance_id:8,stars:2)
# place7 = Place.create!(host_id:7,title:"Riverrun",lng:,lat:,description:"",price_per_night:,region_id:7,number_rooms:,number_beds:,max_guests:,property_type:"",house_rules:"",allegiance_id:5,stars:1)
# place8 = Place.create!(host_id:8,title:"Frostfang Mountains",lng:,lat:,description:"camping",price_per_night:16,region_id:6,number_rooms:,number_beds:,max_guests:,property_type:"",house_rules:"",stars:1)
# place9 = Place.create!(host_id:9,title:"Vaes Dothrak",lng:,lat:,description:"",price_per_night:,region_id:9,number_rooms:,number_beds:,max_guests:,property_type:"",house_rules:"",stars:2)
# place10 = Place.create!(host_id:10,title:"Inn at the Crossroads",lng:,lat:,description:"",price_per_night:249,region_id:7,number_rooms:,number_beds:,max_guests:,property_type:"Bed & Breakfast",house_rules:"",stars:4)
# place11 = Place.create!(host_id:11,title:"Highgarden",lng:,lat:,description:"",price_per_night:,region_id:4,number_rooms:,number_beds:,max_guests:,property_type:"",house_rules:"",allegiance_id:6,stars:5)
# place12 = Place.create!(host_id:12,title:"Casterly Rock",lng:,lat:,description:"",price_per_night:,region_id:5,number_rooms:,number_beds:,max_guests:,property_type:"",house_rules:"",allegiance_id:1,stars:4)
# place13 = Place.create!(host_id:13,title:"The Great Sept of Baelor",lng:,lat:,description:"",price_per_night:,region_id:1,number_rooms:,number_beds:,max_guests:,property_type:"",house_rules:"",stars:2)
# place14 = Place.create!(host_id:14,title:"The Eyrie",lng:,lat:,description:"",price_per_night:,region_id:12,number_rooms:,number_beds:,max_guests:,property_type:"",house_rules:"",allegiance_id:10,stars:3)
# place15 = Place.create!(host_id:15,title:"Pyke",lng:,lat:,description:"",price_per_night:,region_id:5,number_rooms:,number_beds:,max_guests:,property_type:"",house_rules:"",allegiance_id:9,stars:3)
# # place16 = Place.create!(host_id:16,title:"Littlefinger's Brothel",lng:,lat:,description:"",price_per_night:,region_id:1,number_rooms:,number_beds:,max_guests:,property_type:"",house_rules:"",stars:4)
# place17 = Place.create!(host_id:17,title:"Castle Dreadfort",lng:,lat:,description:"",price_per_night:,region_id:2,number_rooms:,number_beds:,max_guests:,property_type:"",house_rules:"",allegiance_id:11,stars:2)
# place18 = Place.create!(host_id:18,title:"Dwelling on the Long Bridge",lng:,lat:,description:"Volantis",price_per_night:,region_id:10,number_rooms:,number_beds:,max_guests:,property_type:"hosue",house_rules:"",stars:3)
# place19 = Place.create!(host_id:19,title:"Spear Tower",lng:,lat:,description:"in Sunspear, capital of Dorne",price_per_night:795,region_id:8,number_rooms:,number_beds:,max_guests:,property_type:"castle",house_rules:"",allegiance_id:12,stars:5)
# place20 = Place.create!(host_id:20,title:"Storm's End",lng:,lat:,description:"",price_per_night:550,region_id:1,number_rooms:,number_beds:,max_guests:,property_type:"castle",house_rules:"",allegiance_id:4,stars:4)
# place21 = Place.create!(host_id:21,title:"Horn Hill",lng:,lat:,description:"",price_per_night:1275,region_id:4,number_rooms:,number_beds:,max_guests:,property_type:"",house_rules:"",allegiance_id:7,stars:5)
# place22 = Place.create!(host_id:22,title:"Dragonstone",lng:,lat:,description:"",price_per_night:,region_id:1,number_rooms:,number_beds:,max_guests:,property_type:"castle",house_rules:"",allegiance_id:4,stars:4)
# place23 = Place.create!(host_id:23,title:"Evenfall Hall",lng:,lat:,description:"",price_per_night:,region_id:1,number_rooms:,number_beds:,max_guests:,property_type:"",house_rules:"",stars:3)
# place24 = Place.create!(host_id:24,title:"Dwelling on Ragman Lane",lng:,lat:,description:"",price_per_night:45,region_id:3,number_rooms:,number_beds:,max_guests:,property_type:"",house_rules:"",stars:5)
# place25 = Place.create!(host_id:25,title:"Lys Resort",lng:,lat:,description:"",price_per_night:,region_id:11,number_rooms:,number_beds:,max_guests:,property_type:"",house_rules:"",stars:5)

PlaceImage.create(place_id:5, url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478063363/Places/houseblackandwhite.png")
PlaceImage.create(place_id:5, url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478063349/Places/houseblackandwhite4.png")
PlaceImage.create(place_id:5, url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478063348/Places/houseblackandwhite3.jpg")
PlaceImage.create(place_id:5, url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478063347/Places/houseblackandwhite2.jpg",caption:"Come on in, we're very hospitable.")
PlaceImage.create(place_id:1, url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478149778/Places/redkeep1.jpg")
PlaceImage.create(place_id:1, url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478149772/Places/redkeep2.jpg")
PlaceImage.create(place_id:1, url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478149777/Places/redkeep3.jpg")
# PlaceImage.create(place_id:21, url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478149775/Places/hornhill2.jpg")
# PlaceImage.create(place_id:21, url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478150052/Places/hornhill3.jpg")
# PlaceImage.create(place_id:21, url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478150050/Places/hornhill4.jpg")
# PlaceImage.create(place_id:11, url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478149779/Places/highgarden.jpg")
# PlaceImage.create(place_id:11, url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478150534/Places/highgarden2.jpg")
# PlaceImage.create(place_id:11, url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478150584/Places/highgarden4.jpg")
PlaceImage.create(place_id:3, url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478150840/Places/winterfell1.jpg")
PlaceImage.create(place_id:3, url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478150842/Places/Winterfell2.jpg")
PlaceImage.create(place_id:3, url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478150842/Places/winterfell3.jpg")
PlaceImage.create(place_id:2, url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478152122/Places/Castle_Black1.jpg")
PlaceImage.create(place_id:2, url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478152119/Places/castleblack2.jpg")
PlaceImage.create(place_id:4, url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478153031/Places/pyramid1.jpg")
PlaceImage.create(place_id:4, url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478153031/Places/pyramid2.jpg",caption:"Check out that view, though")
PlaceImage.create(place_id:4, url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478153035/Places/pyramid3.jpg",caption:"If you see on of these guys, RUN!!!")
PlaceImage.create(place_id:4, url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478153031/Places/pyramid4.jpg")
PlaceImage.create(place_id:4, url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478153034/Places/pyramid5.jpg")
# PlaceImage.create(place_id:6, url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478153498/Places/twins0.jpg")
# PlaceImage.create(place_id:6, url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478153498/Places/twins1.jpg")
# PlaceImage.create(place_id:7, url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478153824/Places/riverrun1.jpg")
# PlaceImage.create(place_id:7, url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478153825/Places/riverrun2.jpg")
# PlaceImage.create(place_id:8, url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478154022/Places/frostfang0.jpg")
# PlaceImage.create(place_id:8, url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478154083/Places/frostfang2.jpg",caption:"Isn't our campsite lovely?")
# PlaceImage.create(place_id:8, url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478154018/Places/frostfang1.jpg",caption:"Pack your fur coat, it's a bit chilly.")
# PlaceImage.create(place_id:9, url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478155203/Places/VaesDothrak0.jpg")
# PlaceImage.create(place_id:9, url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478155213/Places/VaesDothrak1.jpg")
# PlaceImage.create(place_id:9, url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478155196/Places/VaesDothrak2.jpg")
# PlaceImage.create(place_id:9, url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478155198/Places/VaesDothrak4.jpg")
# PlaceImage.create(place_id:9, url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478156379/Places/vaesdothrak5.jpg")
# PlaceImage.create(place_id:10, url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478155702/Places/Inn_at_the_Crossroads1.jpg")
# PlaceImage.create(place_id:10, url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478155702/Places/inncrossroads2.jpg")
# PlaceImage.create(place_id:12, url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478155899/Places/casterlyrock.jpg",caption:"Where your hiking boots. It's all the way at the top and there's no elevator.")
# PlaceImage.create(place_id:13, url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478156386/Places/GreatSept1.jpg")
# PlaceImage.create(place_id:13, url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478156388/Places/GreatSept2.jpg")
# PlaceImage.create(place_id:13, url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478156523/Places/GreatSept3.jpg")
# PlaceImage.create(place_id:14, url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478156833/Places/eyrie1.png")
# PlaceImage.create(place_id:14, url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478156827/Places/eyrie2.jpg")
# PlaceImage.create(place_id:14, url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478156827/Places/eyrie3.jpg",caption:"Don't look down!")
# PlaceImage.create(place_id:15, url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478157525/Places/pyke1.jpg")
# PlaceImage.create(place_id:15, url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478157526/Places/iron2.jpg")
# PlaceImage.create(place_id:15, url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478157532/Places/iron3.jpg")
# PlaceImage.create(place_id:, url:"")
# PlaceImage.create(place_id:, url:"")
# PlaceImage.create(place_id:, url:"")
# PlaceImage.create(place_id:, url:"")
# PlaceImage.create(place_id:, url:"")
# PlaceImage.create(place_id:, url:"")
# PlaceImage.create(place_id:, url:"")
# PlaceImage.create(place_id:, url:"")
# PlaceImage.create(place_id:, url:"")
# PlaceImage.create(place_id:, url:"")

region1 = Region.create!(name:"Crownlands & Stormlands",image_url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478073941/Regions/crownlands.jpg") #6
region2 = Region.create!(name:"The North",image_url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478073940/Regions/the_north.jpg") #2
region3 = Region.create!(name:"Braavos",image_url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478063294/Regions/braavos.jpg") #2
region4 = Region.create!(name:"The Reach",image_url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478073949/Regions/thereach.png") #2
region5 = Region.create!(name:"The Iron Islands & Westerlands",image_url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478073942/Regions/ironislands.jpg") #2
region6 = Region.create!(name:"Beyond the Wall & The Gift",image_url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478073936/Regions/beyondthewall.jpg") #2
region7 = Region.create!(name:"Riverlands",image_url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478073937/Regions/riverlands.jpg") #3
region8 = Region.create!(name:"Dorne",image_url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478073940/Regions/Dorne.jpg") #1
region9 = Region.create!(name:"Dothraki Sea",image_url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478073936/Regions/dothraki_sea.jpg") #1
region10 = Region.create!(name:"Slaver's Bay & Volantis",image_url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478073950/Regions/slaversbay.png") #2
region11 = Region.create!(name:"Pentos & Tyrosh",image_url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478073937/Regions/pentos2.jpg") #1
region12 = Region.create!(name:"The Vale of Arryn",image_url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478073941/Regions/thevale.jpg") #1

# allegiance1 = Allegiance.create!(house_name:"Lannister",flag_image_url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478105489/flags/Lannister.png")
# allegiance2 = Allegiance.create!(house_name:"Stark",flag_image_url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478105490/flags/stark.png")
# allegiance3 = Allegiance.create!(house_name:"Targaryen",flag_image_url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478105490/flags/Targaryen.png")
# allegiance4 = Allegiance.create!(house_name:"Baratheon",flag_image_url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478105489/flags/baratheon.png")
# allegiance5 = Allegiance.create!(house_name:"Tully",flag_image_url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478105490/flags/bolton.png")
# allegiance6 = Allegiance.create!(house_name:"Tyrell",flag_image_url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478105490/flags/tyrell.png")
# allegiance7 = Allegiance.create!(house_name:"Tarly",flag_image_url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478105490/flags/tarly.png")
# allegiance8 = Allegiance.create!(house_name:"Frey",flag_image_url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478144985/flags/house-frey.png")
# allegiance9 = Allegiance.create!(house_name:"Greyjoy",flag_image_url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478105489/flags/greyjoy.png")
# allegiance10 = Allegiance.create!(house_name:"Arryn",flag_image_url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478144983/flags/real_house_arryn.png")
# allegiance11 = Allegiance.create!(house_name:"Bolton",flag_image_url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478144982/flags/real_bolton.png")
# allegiance12 = Allegiance.create!(house_name:"Martell",flag_image_url:"http://res.cloudinary.com/dbsxgncvx/image/upload/v1478144983/flags/house_martell.png")

# booking1 = Booking.create!(place_id:,user_id:2,check_in_date:,check_out_date:,number_of_guests:)
# booking2 = Booking.create!(place_id:,user_id:2,check_in_date:,check_out_date:,number_of_guests:)
# booking3 = Booking.create!(place_id:,user_id:2,check_in_date:,check_out_date:,number_of_guests:)
# booking4 = Booking.create!(place_id:,user_id:2,check_in_date:,check_out_date:,number_of_guests:)
# booking5 = Booking.create!(place_id:,user_id:2,check_in_date:,check_out_date:,number_of_guests:)
# booking6 = Booking.create!(place_id:,user_id:2,check_in_date:,check_out_date:,number_of_guests:)
#
review1 = Review.create!(place_id:1,author_id:3,number_of_stars:2,body:"I hate this place.")
# review2 = Review.create!(place_id:,author_id:,number_of_stars:,body:)
# review3 = Review.create!(place_id:,author_id:,number_of_stars:,body:)
# review4 = Review.create!(place_id:,author_id:,number_of_stars:,body:)
# review5 = Review.create!(place_id:,author_id:,number_of_stars:,body:)
# review6 = Review.create!(place_id:,author_id:,number_of_stars:,body:)
# review7 = Review.create!(place_id:,author_id:,number_of_stars:,body:)
# review8 = Review.create!(place_id:,author_id:,number_of_stars:,body:)
# review9 = Review.create!(place_id:,author_id:,number_of_stars:,body:)
# review10 = Review.create!(place_id:,author_id:,number_of_stars:,body:)
# review11 = Review.create!(place_id:,author_id:,number_of_stars:,body:)
# review12 = Review.create!(place_id:,author_id:,number_of_stars:,body:)
# review13 = Review.create!(place_id:,author_id:,number_of_stars:,body:)
# review14 = Review.create!(place_id:,author_id:,number_of_stars:,body:)
# review15 = Review.create!(place_id:,author_id:,number_of_stars:,body:)
# review16 = Review.create!(place_id:,author_id:,number_of_stars:,body:)
# review17 = Review.create!(place_id:,author_id:,number_of_stars:,body:)
# review18 = Review.create!(place_id:,author_id:,number_of_stars:,body:)
# review19 = Review.create!(place_id:,author_id:,number_of_stars:,body:)
# review20 = Review.create!(place_id:,author_id:,number_of_stars:,body:)
# review21 = Review.create!(place_id:,author_id:,number_of_stars:,body:)
# review22 = Review.create!(place_id:,author_id:,number_of_stars:,body:)
# review23 = Review.create!(place_id:,author_id:,number_of_stars:,body:)
# review24 = Review.create!(place_id:,author_id:,number_of_stars:,body:)
# review25 = Review.create!(place_id:,author_id:,number_of_stars:,body:)
# review26 = Review.create!(place_id:,author_id:,number_of_stars:,body:)
# review27 = Review.create!(place_id:,author_id:,number_of_stars:,body:)
# review28 = Review.create!(place_id:,author_id:,number_of_stars:,body:)
# review29 = Review.create!(place_id:,author_id:,number_of_stars:,body:)
# review30 = Review.create!(place_id:,author_id:,number_of_stars:,body:)
# review31 = Review.create!(place_id:,author_id:,number_of_stars:,body:)
# review32 = Review.create!(place_id:,author_id:,number_of_stars:,body:)
# review33 = Review.create!(place_id:,author_id:,number_of_stars:,body:)
# review34 = Review.create!(place_id:,author_id:,number_of_stars:,body:)
# review35 = Review.create!(place_id:,author_id:,number_of_stars:,body:)
# review36 = Review.create!(place_id:,author_id:,number_of_stars:,body:)
# review37 = Review.create!(place_id:,author_id:,number_of_stars:,body:)
# review38 = Review.create!(place_id:,author_id:,number_of_stars:,body:)
# review39 = Review.create!(place_id:,author_id:,number_of_stars:,body:)
# review40 = Review.create!(place_id:,author_id:,number_of_stars:,body:)
# review41 = Review.create!(place_id:,author_id:,number_of_stars:,body:)
# review42 = Review.create!(place_id:,author_id:,number_of_stars:,body:)
# review43 = Review.create!(place_id:,author_id:,number_of_stars:,body:)
# review44 = Review.create!(place_id:,author_id:,number_of_stars:,body:)
# review45 = Review.create!(place_id:,author_id:,number_of_stars:,body:)
# review46 = Review.create!(place_id:,author_id:,number_of_stars:,body:)
# review47 = Review.create!(place_id:,author_id:,number_of_stars:,body:)
# review48 = Review.create!(place_id:,author_id:,number_of_stars:,body:)
# review49 = Review.create!(place_id:,author_id:,number_of_stars:,body:)
# review50 = Review.create!(place_id:,author_id:,number_of_stars:,body:)
# review51 = Review.create!(place_id:,author_id:,number_of_stars:,body:)
# review52 = Review.create!(place_id:,author_id:,number_of_stars:,body:)
# review53 = Review.create!(place_id:,author_id:,number_of_stars:,body:)
# review54 = Review.create!(place_id:,author_id:,number_of_stars:,body:)
# review55 = Review.create!(place_id:,author_id:,number_of_stars:,body:)
# review56 = Review.create!(place_id:,author_id:,number_of_stars:,body:)
# review57 = Review.create!(place_id:,author_id:,number_of_stars:,body:)
# review58 = Review.create!(place_id:,author_id:,number_of_stars:,body:)
# review59 = Review.create!(place_id:,author_id:,number_of_stars:,body:)
# review60 = Review.create!(place_id:,author_id:,number_of_stars:,body:)
# review61 = Review.create!(place_id:,author_id:,number_of_stars:,body:)
# review62 = Review.create!(place_id:,author_id:,number_of_stars:,body:)
# review63 = Review.create!(place_id:,author_id:,number_of_stars:,body:)
# review64 = Review.create!(place_id:,author_id:,number_of_stars:,body:)
# review65 = Review.create!(place_id:,author_id:,number_of_stars:,body:)
# review66 = Review.create!(place_id:,author_id:,number_of_stars:,body:)
# review67 = Review.create!(place_id:,author_id:,number_of_stars:,body:)
# review68 = Review.create!(place_id:,author_id:,number_of_stars:,body:)
# review69 = Review.create!(place_id:,author_id:,number_of_stars:,body:)
# review70 = Review.create!(place_id:,author_id:,number_of_stars:,body:)
